dist: xenial
language: rust

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly-2019-05-09

install:
- rustup component add rustfmt clippy

script:
- cargo build --all --all-features --verbose
- cargo test --all --all-features --verbose
- cargo clippy --all -- -Dwarnings
- cargo clippy --all --tests -- -Dwarnings
- cargo fmt --all -- --check
- cargo doc --all --no-deps
