dist: xenial
language: rust

matrix:
  include:
    - rust: beta
      os: linux
    - rust: stable
      os: linux
    - os: linux
    - os: windows
    - os: osx

install:
- rustup component add rustfmt clippy

script:
- cargo build --all --all-features --verbose
- cargo test --all --all-features --verbose
- cargo clippy --all -- -Dwarnings
- cargo clippy --all --tests -- -Dwarnings
- cargo fmt --all -- --check
- cargo doc --all --no-deps
