dist: xenial
language: rust

matrix:
  include:
    - rust: beta
      env: CARGO_FLAGS=+beta
      os: linux
    - rust: stable
      env: CARGO_FLAGS=+stable
      os: linux
    - os: linux
    - os: windows
    - os: osx

install:
- rustup component add rustfmt clippy

script:
- cargo build  $CARGO_FLAGS --all --all-features --verbose
- cargo test   $CARGO_FLAGS --all --all-features --verbose
- cargo clippy $CARGO_FLAGS --all -- -Dwarnings
- cargo clippy $CARGO_FLAGS --all --tests -- -Dwarnings
- cargo fmt    $CARGO_FLAGS --all -- --check
- cargo doc    $CARGO_FLAGS --all --no-deps
