[package]
name = "mockiato"
description = "Minimalistic mocking framework, ready for Rust 2018! 🎉"
version = "0.2.0"
authors = [
    "Jan Nils Ferner <jan@myelin.ch>",
    "Ruben Schmidmeister <ruben@myelin.ch>",
    "Jeremy Stucki <jeremy@myelin.ch>",
]
repository = "https://github.com/myelin-ai/mockiato"
homepage = "https://github.com/myelin-ai/mockiato"
documentation = "https://docs.rs/mockiato"
edition = "2018"
license = "MIT"
keywords = [ "test", "mock" ]

[dependencies]
mockiato-codegen = { path = "crates/mockiato-codegen", version = "0.2.0" }

[dev-dependencies]
compiletest_rs = "0.3.14"

[workspace]
members = [
    "crates/mockiato-codegen",
    "crates/mockiato-doc-example",
]
